# YOUR NAME OR TITLE OF YOUR SITE
name: Bram Vandenbussche

# YOUR BRAND/PERSONAL TAGLINE
tagline: Howdy, I'm Bram Vandenbussche. Dad of 5, loving husband, quite into security, something to do with software engineering and all-around tech geek. 

# YOUR/BRAND IMAGE URL
Image_URL: https://secure.gravatar.com/avatar/966ffc611efed95e5f9189873f63d295?s=500

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random/?software,code


# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
baseurl: /

# Default Markdown Engine
markdown: kramdown

google_analytics: G-Q3FM9H7KTE