# YOUR NAME OR TITLE OF YOUR SITE
name: Bram Vandenbussche

# YOUR BRAND/PERSONAL TAGLINE
tagline: Howdy, I'm Bram Vandenbussche. Dad of 5, loving husband, quite into security, something to do with software engineering and all-around tech geek. 

# YOUR/BRAND IMAGE URL
Image_URL: https://secure.gravatar.com/avatar/966ffc611efed95e5f9189873f63d295?s=500

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random/?software,code

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: bramensofie
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: bram.plays.games
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: vandenbusschebr
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter
    
    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: bramvandenbussche
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # REDDIT
  - Name: Reddit
    URL: http://reddit.com/u
    Username: vandenbusscheb
    Color: '#FF4500'
    Icon-Class: fab fa-reddit-alien

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: bramvandenbussche
    Color: '#6e5494'
    Icon-Class: fab fa-github

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

    # PINTEREST
  - Name: Pinterest
    URL: https://pinterest.com
    Username: 'arbje'
    Color: '#E60023'
    Icon-Class: fab fa-pinterest

  #    # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username: 
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok

    # CUSTOM LINK
  # - Name: Website
  #   URL: https://bramvandenbussche.be
  #   Icon-Class: fas fa-link
  #   Color: '#ffb142'
  #   Text_Color: '#ffffff'

    # EMAIL
  - Name: Email
    URL: 'mailto:bram@vandenbussche.me'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
baseurl: /

# Default Markdown Engine
markdown: kramdown

google_analytics: G-Q3FM9H7KTE